services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Derhansen\FemanagerDmailSubscribe\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  In2code\Femanager\Controller\NewController: '@Derhansen\FemanagerDmailSubscribe\Controller\NewController'
  In2code\Femanager\Controller\EditController: '@Derhansen\FemanagerDmailSubscribe\Controller\EditController'
